id: A6AC46A14
base_file: f551E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:54:46.804302
  last_modified_at: 2022-05-31 06:54:46.804326
